### ISSUE TITLE
A note should be added in the README about the Asset Pipeline

### ISSUE THREAD

**Issue by simonc** [tye/rubyception#13]
When using rubyception in production, it doesn't find its CSS files `shCore.css` and `shThemeDefault.css` unless you add it in your precompiled_assets.

Maybe a note should be added about it in the README file.

``` ruby
# config/environments/production.rb

Example::Application.configure do
  config.assets.precompile += %w( rubyception/shCore.css rubyception/shThemeDefault.css )
end
```

**Comment by tye** [comment]
Rubyception isnt meant to be used in production at all. I've made that more clear in the README
