### ISSUE TITLE
Could not log "sql.active_record" event

### ISSUE THREAD

**Issue by sukhchander** [tye/rubyception#18]
integrating rubyception into an existing app.

setup:
ruby 1.9.3p194
rails 3.2.8
thin 1.5.0

result:

``` code
=> Booting Thin
=> Rails 3.2.8 application starting in development on http://0.0.0.0:80
=> Call with -d to detach
=> Ctrl-C to shutdown server
Could not log "sql.active_record" event. NoMethodError: undefined method `<<' for nil:NilClass
Could not log "sql.active_record" event. NoMethodError: undefined method `<<' for nil:NilClass
Could not log "sql.active_record" event. NoMethodError: undefined method `<<' for nil:NilClass
Could not log "sql.active_record" event. NoMethodError: undefined method `<<' for nil:NilClass
>> Thin web server (v1.5.0 codename Knife)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:80, CTRL+C to stop
```

localhost/rubyception yields an empty screen

**Comment by tye** [comment]
This should be fixed with the latest version of rubyception.
Let me know if you still get these errors.

**Comment by sukhchander** [comment]
works. thanks.

btw, what was/were the issue(s)?

**Comment by phocke** [comment]
I've got the same issue with rails 3.2.11

**Comment by chanukyay** [comment]
Same Issue. Please help how to fix it 

ruby '2.3.0'
'rails', '5.0.2'
 WEBrick 1.3.1
rubyception 0.2.0


Started GET "/rubyception" for 127.0.0.1 at 2017-11-17 15:28:10 +0530
Could not log "sql.active_record" event. NoMethodError: undefined method `<<' for nil:NilClass ["/XXX/XXX/.rvm/gems/ruby-2.3.0/gems/rubyception-0.2.0/lib/rubyception/subscriber.rb:26:in `sql'"]
